CREATE TABLE IF NOT EXISTS PRODUCTS (
 PRODUCT_ID TEXT,
 PRODUCT_NAME TEXT,
 SUPPLIER_ID TEXT,
 CATEGORY_ID TEXT,
 UNIT TEXT,
 PRICE REAL 
);

INSERT INTO PRODUCTS( PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES 
 ('1','CHAIS','1','1','10 BOXES*20 BAGS' , 18),
 ('2','NUTELLA','3','3','90 JARS', 40),
 ('3','MIXED FRUIT JAM','7','8', '20 BOTTLES', 100),
 ('4','DAIRY MILK','9','29','20 PACKETS', 124),
 ('5','BUBBLY','23','60','30 PACKETS', 20);

-- QUERY TO COUNT THE NUMBER OF PRODUCTS
SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS;

-- QUERY TO FIND THE AVERAGE PRICE  OF PRODUCTS
SELECT AVG(PRICE) AS Average_Price
FROM products;

--QUERY TO FIND THE TOTAL  PRICE OF PRODUCTS
SELECT SUM(PRICE) AS Total_Price
FROM PRODUCTS;

