CREATE TABLE IF NOT EXISTS ANIMALS(
 S_NO INT,
 ANIMALS_SPECIES TEXT,
 ANIMALS_UNIT INT 
);

INSERT INTO ANIMALS(S_NO,ANIMALS_SPECIES, ANIMALS_UNIT) VALUES
 (1,'CAT',20),
 (2,'HORSE',3),
 (3,'DOGS',25);

SELECT COUNT(S_NO) AS ANIMAL_COUNT
FROM ANIMALS;

SELECT SUM(ANIMALS_UNIT) AS Total_Animals
FROM ANIMALS;

